main: net.heavin.StaffEssentials.AdminCore
version: 1.0
name: AdminCore
api-version: 1.16
commands:
  admincore:
    description: Main Command for the plugin
    aliases: [admin, ac]
  report:
  warning:
    aliases: [warn]