main: net.heavin.StaffEssentials.StaffHeavinCore
version: 1.0
name: AdminCore
api-version: 1.13
commands:
  staff:
    description: Main Command for the plugin
    aliases: [staffcore, sc]
  kick:
    description: Kick a player
  ban:
    description: Ban a player
  unban:
    description: Unban a player